namespace CampusEvents.Models;

/// <summary>
/// Represents a ticket for an event in the Campus Events system.
/// Contains ticket information, unique identifier, QR code generation data,
/// and redemption status for event entry validation.
/// </summary>
/// <remarks>
/// The Ticket entity represents a user's claim to attend a specific event.
/// Each ticket is unique and contains information needed for QR code generation
/// and validation at the event.
/// 
/// Key Features:
/// - Unique ticket code for identification
/// - QR code generation from unique code
/// - Redemption tracking (claimed vs redeemed)
/// - Timestamp tracking (claimed at, redeemed at)
/// - One ticket per user per event (enforced in business logic)
/// 
/// Business Rules:
/// - UniqueCode must be unique across all tickets (enforced by unique index)
/// - One ticket per user per event (enforced in CarpoolService/TicketService)
/// - Cannot claim ticket if event is at capacity
/// - Cannot claim ticket if event is in the past
/// - QR code generated on-demand from UniqueCode using TicketSigningService
/// - Ticket can only be redeemed once
/// - RedeemedAt is set when ticket is validated via QR scanner
/// 
/// QR Code Generation:
/// - QR code contains HMAC-SHA256 signed token
/// - Token includes: EventId, TicketId, UniqueCode, Expiry
/// - Token expires 24 hours after event date
/// - Token signature prevents forgery
/// - Generated by TicketSigningService.SignTicket()
/// 
/// Ticket Lifecycle:
/// 1. User claims/purchases ticket
/// 2. Ticket created with UniqueCode and ClaimedAt timestamp
/// 3. QR code generated on-demand when user views ticket
/// 4. User presents QR code at event
/// 5. Organizer scans QR code
/// 6. Ticket validated via TicketSigningService.VerifyTicket()
/// 7. Ticket marked as redeemed (IsRedeemed = true, RedeemedAt set)
/// 
/// Security:
/// - UniqueCode is the canonical source of truth
/// - QR codes are signed tokens, not just encoded data
/// - Token verification prevents forgery
/// - Expiry prevents reuse after event
/// 
/// Relationships:
/// - Many-to-One: Ticket → Event (ticket is for an event)
/// - Many-to-One: Ticket → User (ticket is owned by a user)
/// 
/// Validation:
/// - UniqueCode: Required, unique (enforced by database index)
/// - EventId: Required, must reference existing event
/// - UserId: Required, must reference existing user
/// 
/// Example Usage:
/// ```csharp
/// // Create ticket when user claims it
/// var ticket = new Ticket
/// {
///     EventId = eventId,
///     UserId = userId,
///     UniqueCode = GenerateUniqueCode(), // e.g., "TKT-2025-001"
///     ClaimedAt = DateTime.UtcNow,
///     IsRedeemed = false
/// };
/// 
/// // Generate QR code token
/// var qrToken = _ticketSigningService.SignTicket(
///     ticket.EventId,
///     ticket.Id,
///     ticket.UniqueCode,
///     ticket.Event.EventDate
/// );
/// 
/// // Validate ticket at event
/// var validationResult = _ticketSigningService.VerifyTicket(qrToken);
/// if (validationResult?.IsValid == true)
/// {
///     ticket.IsRedeemed = true;
///     ticket.RedeemedAt = DateTime.UtcNow;
///     await _context.SaveChangesAsync();
/// }
/// ```
/// </remarks>
public class Ticket
{
    /// <summary>
    /// Unique identifier for the ticket
    /// </summary>
    public int Id { get; set; }
    
    /// <summary>
    /// Foreign key to Event table - the event this ticket is for
    /// </summary>
    public int EventId { get; set; }
    
    /// <summary>
    /// Foreign key to User table - the user who claimed/purchased this ticket
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Canonical source of truth for ticket verification.
    /// QR codes are generated on-demand from this value.
    /// </summary>
    public required string UniqueCode { get; set; }

    /// <summary>
    /// Timestamp when the ticket was claimed/purchased
    /// </summary>
    public DateTime ClaimedAt { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// Timestamp when the ticket was redeemed at the event (null if not redeemed)
    /// </summary>
    public DateTime? RedeemedAt { get; set; }
    
    /// <summary>
    /// Whether the ticket has been redeemed/used at the event
    /// </summary>
    public bool IsRedeemed { get; set; } = false;

    // Navigation properties
    
    /// <summary>
    /// Event this ticket is for
    /// </summary>
    public Event Event { get; set; } = null!;
    
    /// <summary>
    /// User who owns this ticket
    /// </summary>
    public User User { get; set; } = null!;
}
